import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "../components/provider";
import Header from "../components/header";
import { HookProvider } from "../components/hookContext";
import { Suspense } from "react";
import "@rainbow-me/rainbowkit/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <HookProvider>
            <Header />
            <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
          </HookProvider>
        </Provider>
      </body>
    </html>
  );
}
