deploy:
	forge script script/Nezlobin_Simulation/01_Deploy.s.sol:Deployer --rpc-url 127.0.0.1:8545 --broadcast
initialize:
	forge script script/Nezlobin_Simulation/02_Initialize.s.sol:PoolInitialize --rpc-url 127.0.0.1:8545 --broadcast
addliq:
	forge script script/Nezlobin_Simulation/03_AddLiq.s.sol:PoolLiq --rpc-url 127.0.0.1:8545 --broadcast
swap:
	forge script script/Nezlobin_Simulation/04_Swap.s.sol:Swap --rpc-url 127.0.0.1:8545 --broadcast
check:
	forge script script/Nezlobin_Simulation/05_Check.s.sol:Check --rpc-url 127.0.0.1:8545 --broadcast